export type Lang = "he" | "en";

export const strings = {
  // Top nav
  searchPlaceholder: { he: "חיפוש מועמדים...", en: "Search candidates..." },
  search: { he: "חיפוש", en: "Search" },
  notifications: { he: "התראות", en: "Notifications" },
  settings: { he: "הגדרות", en: "Settings" },
  theme: { he: "ערכת נושא", en: "Theme" },
  themeLight: { he: "בהיר", en: "Light" },
  themeDark: { he: "כהה", en: "Dark" },
  language: { he: "שפה", en: "Language" },
  langHebrew: { he: "עברית", en: "Hebrew" },
  langEnglish: { he: "אנגלית", en: "English" },

  // Dashboard
  greeting: { he: "שלום ליאת", en: "Hi Liat" },
  greetingSub: {
    he: "3 מועמדים מחכים לסקירה השבוע",
    en: "3 candidates awaiting review this week",
  },
  statInterviewsThisWeek: { he: "ראיונות השבוע", en: "Interviews this week" },
  statAwaiting: { he: "מחכים לסקירה", en: "Awaiting review" },
  statAdvanced: { he: "עברו לסבב הבא", en: "Advanced" },
  statScheduled: { he: "מתוזמנים", en: "Scheduled" },
  recentCandidates: { he: "מועמדים אחרונים", en: "Recent candidates" },
  filterAll: { he: "הכל", en: "All" },
  filterAwaiting: { he: "ממתינים", en: "Awaiting" },
  filterAdvanced: { he: "עברו לסבב הבא", en: "Advanced" },
  filterOnHold: { he: "בהמתנה", en: "On hold" },
  newInterview: { he: "ראיון חדש", en: "New interview" },
  compareCandidates: { he: "השווה מועמדים", en: "Compare candidates" },
  compareAllN: { he: "השווה את 5 המועמדים", en: "Compare all 5 candidates" },
  sideBySide: { he: "השוואה זה לצד זה", en: "Side-by-side comparison" },
  viewSummary: { he: "צפה בסיכום", en: "View summary" },
  justAnalyzed: { he: "נותח עכשיו", en: "Just analyzed" },

  // Status pills
  statusAwaiting: { he: "ממתין לסקירה", en: "Awaiting review" },
  statusAdvanced: { he: "עבר לסבב הבא", en: "Advanced" },
  statusOnHold: { he: "בהמתנה", en: "On hold" },

  // Candidate detail
  candidatesBreadcrumb: { he: "מועמדים", en: "Candidates" },
  interview: { he: "ראיון", en: "Interview" },
  firstRound: { he: "סבב ראשון", en: "First round" },
  insightSource: { he: "מקור", en: "Source" },
  sourceResume: { he: "קו\"ח", en: "Resume" },
  sourceLinkedIn: { he: "לינקדאין", en: "LinkedIn" },
  sourceScreen: { he: "ראיון ראשוני", en: "Initial screen" },
  newInterviewTitle: { he: "ראיון חדש", en: "New interview" },
  newInterviewBody: {
    he: "כאן יתאפשר להעלות הקלטת ראיון חדשה. הכלי יעבד את ההקלטה אוטומטית — תמלול, חוזקות, פתוחים, ומשימות — ויוסיף את המועמד לדשבורד.",
    en: "This is where you'd upload a new interview recording. The tool will auto-process it — transcript, strengths, open items, and tasks — and add the candidate to the dashboard.",
  },
  newInterviewComingSoon: {
    he: "בקרוב — זהו דמו",
    en: "Coming soon — this is a demo",
  },
  uploadRecording: {
    he: "העלה הקלטה",
    en: "Upload recording",
  },
  cancel: { he: "ביטול", en: "Cancel" },
  emptyStateNoResults: {
    he: "אין מועמדים בקטגוריה הזו",
    en: "No candidates in this category",
  },
  notif1: {
    he: "Guy Grassiano נותח עכשיו",
    en: "Guy Grassiano was just analyzed",
  },
  notif1Meta: { he: "לפני 12 דקות", en: "12 minutes ago" },
  notif2: {
    he: "Eitan M. עבר לסבב הבא",
    en: "Eitan M. advanced to round 2",
  },
  notif2Meta: { he: "אתמול", en: "Yesterday" },
  notif3: {
    he: "תזכורת: ליישר ציפיות שכר עם גיא לפני סוף השבוע",
    en: "Reminder: align salary expectations with Guy before EOW",
  },
  notif3Meta: { he: "לפני שעתיים", en: "2 hours ago" },
  markAllRead: { he: "סמן הכל כנקרא", en: "Mark all as read" },
  noNotifications: { he: "אין התראות חדשות", en: "No new notifications" },
  exportPdf: { he: "ייצוא PDF", en: "Export PDF" },
  sendToVPAI: { he: "שלח ל-VP AI", en: "Send to VP AI" },
  scheduleSecondRound: { he: "קבע סבב שני", en: "Schedule round 2" },
  fitHigh: {
    he: "התאמה גבוהה לתפקיד — חזק במיוחד בבנייה בפועל ובחשיבת אדופציה",
    en: "Strong fit — especially in hands-on building and adoption mindset",
  },
  summaryBody: {
    he: "הסיכום נוצר אוטומטית מתוך תמלול של 47 דקות שיחה. שלוש חוזקות מרכזיות זוהו, וכן שלושה פתוחים שכדאי לסגור לפני סבב שני.",
    en: "Auto-generated from a 47-minute interview transcript. Three key strengths identified, plus three open items to close before round 2.",
  },
  lastUpdated: { he: "עודכן לפני 12 דקות", en: "Updated 12 min ago" },
  keyStrengths: { he: "חוזקות מרכזיות", en: "Key strengths" },
  whatHeSaid: { he: "מה גיא אמר על זה:", en: "What Guy said:" },
  openItems: { he: "פתוחים לסגירה", en: "Open items" },
  nextSteps: { he: "צעדים מומלצים", en: "Recommended next steps" },
  transcriptTitle: { he: "תמלול מלא של השיחה", en: "Full interview transcript" },
  transcriptMeta: {
    he: '47 דקות · נוצר ע"י Dwight, סוכן אישי',
    en: "47 minutes · Generated by Dwight, personal agent",
  },
  showTranscript: { he: "הצג תמלול", en: "Show transcript" },
  hideTranscript: { he: "הסתר תמלול", en: "Hide transcript" },
  compareWithOthers: { he: "השווה עם מועמדים אחרים", en: "Compare with others" },

  // Strengths (data lives in two languages too)
  strength1Title: { he: "רקע יזמי ובנייה בפועל", en: "Founder + hands-on builder" },
  strength1Desc: {
    he: "הקים והפעיל עסק שעובד היום עם מערכות AI שהוא בנה — מייעץ ובעל מניות.",
    en: "Founded and runs a live business operated by AI systems he built — now advisor + shareholder.",
  },
  strength2Title: {
    he: "שליטה עמוקה בכלי AI מודרניים",
    en: "Deep fluency with modern AI tooling",
  },
  strength2Desc: {
    he: "עובד עם Claude Code, Codex ו-MCP — נכנס לכל כלי חדש מהר.",
    en: "Works with Claude Code, Codex and MCP — adopts new tools within days.",
  },
  strength3Title: {
    he: "חשיבת אדופציה צולבת-תחומים",
    en: "Cross-functional adoption mindset",
  },
  strength3Desc: {
    he: "מעביר ידע AI לאנשים לא-טכניים — חברים, קולגות ובני משפחה.",
    en: "Teaches AI to non-technical people — friends, colleagues, family.",
  },

  // Open items
  open1Title: { he: "ציפיות שכר", en: "Compensation expectations" },
  open1Body: {
    he: "לא נמסר טווח בשיחה. מומלץ ליישר ציפיות לפני סבב שני.",
    en: "No range disclosed in the call. Align expectations before round 2.",
  },
  open2Title: { he: "עומק Python", en: "Python depth" },
  open2Body: {
    he: 'דיווח עצמי: "מספיק טוב עם AI". כדאי לבדוק עומק עצמאי בסבב טכני.',
    en: 'Self-assessed as "good enough with AI." Probe independent depth in the technical round.',
  },
  open3Title: { he: "הצגת תיק עבודות", en: "Portfolio walkthrough" },
  open3Body: {
    he: "הוזכר עסק AR לאירועים — שווה לראות הדגמה חיה.",
    en: "Mentioned a live AR-events business — worth a live walkthrough.",
  },

  // Next steps
  step1: {
    he: "ליישר ציפיות שכר עם המועמד",
    en: "Align on compensation expectations",
  },
  step2: { he: "לקבוע ראיון עם VP AI", en: "Schedule interview with VP AI" },
  step3: {
    he: "לבקש סיור בעסק ה-AR החי",
    en: "Request live AR business walkthrough",
  },

  // Compare page
  compareTitle: { he: "השוואת מועמדים", en: "Compare candidates" },
  compareSub: {
    he: "AI Adoption Engineer · 5 מועמדים נבחרו",
    en: "AI Adoption Engineer · 5 candidates selected",
  },
  shareWithVPAI: { he: "שתף עם VP AI", en: "Share with VP AI" },
  scrollHint: {
    he: "← החלק את הטבלה כדי לראות עוד",
    en: "Swipe the table to see more →",
  },
  bottomLine: { he: "שורה תחתונה", en: "Bottom line" },
  bottomLineBody: {
    he: "גיא בולט בתבנית הרחבה — שילוב של בנייה בפועל, שליטה בכלים מתקדמים, וחשיבת אדופציה צולבת. איתן חזק יותר בעומק Python אבל מצומצם יותר בתפיסה צולבת-תחומים. מומלץ: להעביר את גיא לראיון עם VP AI, ולהמשיך במקביל עם איתן כגיבוי טכני.",
    en: "Guy stands out on the broad pattern — combining hands-on building, advanced tooling fluency, and cross-functional adoption thinking. Eitan is deeper in Python but narrower cross-functionally. Recommended: advance Guy to the VP AI interview, keep Eitan parallel as a technical backup.",
  },
  scheduleWithGuy: {
    he: "קבע ראיון עם גיא",
    en: "Schedule interview with Guy",
  },
  keepEitanLoop: {
    he: "שמור גם את איתן בלולאה",
    en: "Keep Eitan in the loop too",
  },
  backToDashboard: { he: "חזור לדשבורד", en: "Back to dashboard" },
  candidatesSelected: { he: "5 מועמדים נבחרו", en: "5 candidates selected" },

  // Compare dimensions
  dimOverallFit: { he: "התאמה כללית", en: "Overall fit" },
  dimAITooling: { he: "שליטה בכלי AI", en: "AI tooling fluency" },
  dimBuilder: { he: "רקע יזמי / בנייה בפועל", en: "Founder / hands-on builder" },
  dimCrossFunctional: { he: "חשיבת אדופציה צולבת", en: "Cross-functional adoption" },
  dimPython: { he: "עומק הנדסי (Python)", en: "Engineering depth (Python)" },
  dimComm: { he: "תקשורת ושפות", en: "Communication & languages" },
  dimRampUp: { he: "זמן לרמפ-אפ", en: "Ramp-up time" },
  dimOpenItems: { he: "פתוחים לסגירה", en: "Open items" },

  // Roles, dates phrasing
  roleAIAdoption: { he: "AI Adoption Engineer", en: "AI Adoption Engineer" },

  // Footer
  footerCredit: {
    he: "Created and orchestrated by Guy Grassiano",
    en: "Created and orchestrated by Guy Grassiano",
  },
} as const;

export type StringKey = keyof typeof strings;

export function t(key: StringKey, lang: Lang): string {
  return strings[key][lang];
}
